# Generated by Django 4.2.6 on 2023-10-25 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0005_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField(null=True)),
                ('payment_mode', models.CharField(default=True, max_length=50)),
                ('payment_id', models.CharField(blank=True, default=True, max_length=50, null=True)),
                ('messages', models.TextField(blank=True, default=True, null=True)),
                ('tracking_no', models.CharField(default=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('od_status', models.CharField(choices=[('Return', 'Return'), ('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Processing', 'Processing'), ('Cancelled', 'Cancelled'), ('Shipped', 'Shipped')], default='pending', max_length=150, null=True)),
                ('Profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
