# Generated by Django 4.2.6 on 2023-10-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Profile',
            new_name='profile',
        ),
        migrations.AlterField(
            model_name='order',
            name='od_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Delivered', 'Delivered'), ('Return', 'Return'), ('Cancelled', 'Cancelled'), ('Shipped', 'Shipped')], default='pending', max_length=150, null=True),
        ),
    ]
