# Generated by Django 4.2.6 on 2023-10-30 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_order_is_cancelled_alter_order_od_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='od_status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Return', 'Return'), ('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Shipped', 'Shipped')], default='pending', max_length=150, null=True),
        ),
    ]
