# Generated by Django 4.2.6 on 2023-11-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_alter_order_od_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='od_status',
            field=models.CharField(choices=[('Return', 'Return'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Processing', 'Processing'), ('Cancelled', 'Cancelled'), ('Pending', 'Pending')], default='pending', max_length=150, null=True),
        ),
    ]
