# Generated by Django 4.2.4 on 2023-11-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0042_wallet_transaction_alter_order_od_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='transaction',
        ),
        migrations.AddField(
            model_name='wallet',
            name='date',
            field=models.DateField(auto_now_add=True, default='2023-02-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallet',
            name='transaction_type',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='od_status',
            field=models.CharField(choices=[('Shipped', 'Shipped'), ('Return', 'Return'), ('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Processing', 'Processing'), ('Cancelled', 'Cancelled')], default='pending', max_length=150, null=True),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
