# Generated by Django 4.2.4 on 2023-11-15 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0043_remove_wallet_transaction_wallet_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='date',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='transaction_type',
        ),
        migrations.AlterField(
            model_name='order',
            name='od_status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Shipped', 'Shipped'), ('Processing', 'Processing'), ('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Return', 'Return')], default='pending', max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=50)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='wallet',
            name='transactions',
            field=models.ManyToManyField(to='user.transaction'),
        ),
    ]
