# Generated by Django 4.2.4 on 2023-11-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0044_remove_wallet_date_remove_wallet_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='od_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Return', 'Return'), ('Processing', 'Processing'), ('Cancelled', 'Cancelled'), ('Delivered', 'Delivered')], default='pending', max_length=150, null=True),
        ),
    ]
