# Generated by Django 4.2.4 on 2023-11-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0048_alter_order_od_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='od_status',
            field=models.CharField(choices=[('Return', 'Return'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Shipped', 'Shipped'), ('Processing', 'Processing'), ('Pending', 'Pending')], default='pending', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
