# Generated by Django 4.2.4 on 2023-11-17 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0053_alter_order_od_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='od_status',
            field=models.CharField(choices=[('Shipped', 'Shipped'), ('Return', 'Return'), ('Delivered', 'Delivered'), ('Processing', 'Processing'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled')], default='pending', max_length=150, null=True),
        ),
    ]
