# Generated by Django 4.2.4 on 2023-11-21 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0054_alter_order_od_status_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='od_status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Processing', 'Processing'), ('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Return', 'Return')], default='pending', max_length=150, null=True),
        ),
    ]
