# Generated by Django 4.2.6 on 2023-11-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0060_alter_order_od_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='od_status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Return', 'Return'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Cancelled', 'Cancelled')], default='pending', max_length=150, null=True),
        ),
    ]
