# Generated by Django 4.2.6 on 2023-12-12 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0065_alter_order_od_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='od_status',
            field=models.CharField(choices=[('Return', 'Return'), ('Cancelled', 'Cancelled'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Pending', 'Pending'), ('Delivered', 'Delivered')], default='pending', max_length=150, null=True),
        ),
    ]
