# Generated by Django 4.2.6 on 2023-12-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0071_alter_order_od_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='od_status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Processing', 'Processing'), ('Pending', 'Pending'), ('Return', 'Return'), ('Shipped', 'Shipped'), ('Cancelled', 'Cancelled')], default='pending', max_length=150, null=True),
        ),
    ]
