# Generated by Django 4.2.6 on 2024-02-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0076_alter_order_od_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='od_status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Shipped', 'Shipped'), ('Pending', 'Pending'), ('Processing', 'Processing'), ('Delivered', 'Delivered'), ('Return', 'Return')], default='pending', max_length=150, null=True),
        ),
    ]
