# Generated by Django 4.2.6 on 2024-02-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0078_alter_order_od_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='od_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Return', 'Return'), ('Cancelled', 'Cancelled')], default='pending', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ordernote',
            field=models.TextField(blank=True, null=True),
        ),
    ]
