# Generated by Django 4.2.6 on 2024-02-03 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0079_alter_order_od_status_alter_profile_ordernote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='od_status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Delivered', 'Delivered'), ('Shipped', 'Shipped'), ('Cancelled', 'Cancelled'), ('Pending', 'Pending'), ('Return', 'Return')], default='pending', max_length=150, null=True),
        ),
    ]
