# Generated by Django 5.0.1 on 2024-02-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0079_alter_order_od_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='od_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Return', 'Return'), ('Shipped', 'Shipped'), ('Cancelled', 'Cancelled'), ('Processing', 'Processing'), ('Delivered', 'Delivered')], default='pending', max_length=150, null=True),
        ),
    ]
