<<<<<<< HEAD
# Generated by Django 5.0.1 on 2024-02-02 10:02
=======
# Generated by Django 4.2.6 on 2024-02-03 04:17
>>>>>>> cf837daeb805dab9e9974ceb33970753ac403a06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('user', '0079_alter_order_od_status'),
=======
        ('user', '0079_alter_order_od_status_alter_profile_ordernote'),
>>>>>>> cf837daeb805dab9e9974ceb33970753ac403a06
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='od_status',
<<<<<<< HEAD
            field=models.CharField(choices=[('Pending', 'Pending'), ('Return', 'Return'), ('Shipped', 'Shipped'), ('Cancelled', 'Cancelled'), ('Processing', 'Processing'), ('Delivered', 'Delivered')], default='pending', max_length=150, null=True),
=======
            field=models.CharField(choices=[('Processing', 'Processing'), ('Delivered', 'Delivered'), ('Shipped', 'Shipped'), ('Cancelled', 'Cancelled'), ('Pending', 'Pending'), ('Return', 'Return')], default='pending', max_length=150, null=True),
>>>>>>> cf837daeb805dab9e9974ceb33970753ac403a06
        ),
    ]
