version: '3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: bag 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - project_default

  django:
    build:
      context: .
      dockerfile: DockerFile  
    command: python project/manage.py runserver 0.0.0.0:8000 
    volumes:
      - ./project:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - project_default

networks:
  project_default:
    external: true
