# Generated by Django 4.2.4 on 2023-11-09 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_cart_offer_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
