# Generated by Django 4.2.4 on 2023-11-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_delete_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='offer_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
