# Generated by Django 4.2.4 on 2023-11-15 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_wishlist_offer_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='offer_price',
        ),
    ]
