# Generated by Django 4.2.4 on 2023-11-15 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_wishlist_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='price',
            new_name='offer_price',
        ),
    ]
