# Generated by Django 4.2.6 on 2023-10-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0003_product_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
