# Generated by Django 4.2.6 on 2023-10-16 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0006_alter_productimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_side.product'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='Image',
            field=models.ImageField(null=True, upload_to='product_image/'),
        ),
    ]
