# Generated by Django 4.2.6 on 2023-10-16 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0007_remove_productimage_image_alter_productimage_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='Image',
            new_name='image',
        ),
    ]
