# Generated by Django 4.2.6 on 2023-11-04 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0009_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='discount_amount',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_side.offer'),
        ),
    ]
