# Generated by Django 4.2.4 on 2023-11-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0012_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='start_date',
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
