# Generated by Django 4.2.4 on 2023-11-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0013_remove_coupon_end_date_remove_coupon_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='is_available',
        ),
        migrations.AddField(
            model_name='offer',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
