# Generated by Django 4.2.4 on 2023-11-07 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0014_remove_offer_is_available_offer_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_coupon',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_side.coupon'),
        ),
    ]
