# Generated by Django 4.2.4 on 2023-11-09 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0016_alter_offer_discount_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='min_price',
        ),
    ]
