# Generated by Django 4.2.4 on 2023-11-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0017_remove_coupon_min_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
