# Generated by Django 4.2.4 on 2023-11-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0019_alter_coupon_coupon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='offer',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
    ]
