# Generated by Django 4.2.6 on 2023-11-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0020_alter_coupon_coupon_code_alter_offer_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='min_price',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
